### ISSUE TITLE
Snikket container is unhealthy

### ISSUE THREAD

**Issue by xcme** [snikket-im/snikket-server#61] opened 2021-09-08 20:14 UTC
I'm trying to install my own server and use it with reverse_proxy. When I'm starting all containers the "snikket" got "unhealthy" after about 2 minutes and on my domains (via port 80) I see in browser the info that snikket is starting and obtaining sertificates but it never ends. Same as for #40.

What should I check first in order to solve it? DNS are find and I put configuration from reverse proxy in nginx config.

One more thing, in
```ss -4 -na```

 output I see only 5080 port, but not 5443, despite I have lines
```
SNIKKET_TWEAK_HTTP_PORT=5080
SNIKKET_TWEAK_HTTPS_PORT=5443
```

in snikket.conf

Thanks in advance

**Comment by mwild1** [comment] 2021-09-08 21:47
Hi, the most likely explanation is that certificates failed to be obtained for some reason.

You can access the debug log with the following command in the directory where you put the docker-compose.yml:

```
docker-compose exec snikket_certs cat /var/log/letsencrypt/letsencrypt.log
```

This file will likely contain some errors like `urn:ietf:params:acme:error:unauthorized` along with some details about why the authorization failed.

**Comment by xcme** [comment] 2021-09-09 17:34
Thanks for the answer. I checked and see 403 errors during the process and then it ends up with:
```
2021-09-09 00:27:11,007:DEBUG:certbot.plugins.webroot:All challenges cleaned up
2021-09-09 00:27:11,007:DEBUG:certbot.log:Exiting abnormally:
Traceback (most recent call last):
  File "/usr/bin/certbot", line 11, in <module>
    load_entry_point('certbot==0.31.0', 'console_scripts', 'certbot')()
  File "/usr/lib/python3/dist-packages/certbot/main.py", line 1365, in main
    return config.func(config, plugins)
  File "/usr/lib/python3/dist-packages/certbot/main.py", line 1250, in certonly
    lineage = _get_and_save_cert(le_client, config, domains, certname, lineage)
  File "/usr/lib/python3/dist-packages/certbot/main.py", line 121, in _get_and_save_cert
    lineage = le_client.obtain_and_enroll_certificate(domains, certname)
  File "/usr/lib/python3/dist-packages/certbot/client.py", line 410, in obtain_and_enroll_certificate
    cert, chain, key, _ = self.obtain_certificate(domains)
  File "/usr/lib/python3/dist-packages/certbot/client.py", line 353, in obtain_certificate
    orderr = self._get_order_and_authorizations(csr.data, self.config.allow_subset_of_names)
  File "/usr/lib/python3/dist-packages/certbot/client.py", line 389, in _get_order_and_authorizations
    authzr = self.auth_handler.handle_authorizations(orderr, best_effort)
  File "/usr/lib/python3/dist-packages/certbot/auth_handler.py", line 93, in handle_authorizations
    "Challenges failed for all domains")
certbot.errors.AuthorizationError: Challenges failed for all domains
```

Previous attempt happened 4 hours 15 minutes before, but last 19 hours no changes in log. How often should it try to get certificates and how can I force it to perform a new attempt?

**Comment by xcme** [comment] 2021-09-09 19:13
I tried docker-compose plus up/down/stop/restart but this container doesn't want to retry it's request.

Sorry, I'm not a big expert with docker.

And another one question. If I use other domains on my site and going to use separate directory "/var/www/chat.example.com/" for snikket, then should I change something in configuration? For my other sites I use the "root" parameter in nginx.conf, but the example for snikket doesn't contain this parameter.

The certbot got 403 last attempt (the post above) and I'm searching for reason of that. It could be wrong path or permissions. Does certbot need write permissions to create ".well-known/acme-challenge" withing the site directory outside the container?

Thanks

**Comment by vncloudsco** [comment] 2021-09-16 04:12
this error is repeating with me can someone help me?
```
root@xmpp:/etc/snikket# docker ps
CONTAINER ID   IMAGE                               COMMAND                  CREATED         STATUS                     PORTS     NAMES
4a650e4cf88a   snikket/snikket-web-portal:beta     "/bin/sh /entrypoint…"   9 minutes ago   Up 9 minutes (healthy)               snikket-portal
d665319ea907   snikket/snikket-web-proxy:beta      "/usr/bin/tini /bin/…"   9 minutes ago   Up 9 minutes                         snikket-proxy
8fe2d6d16610   snikket/snikket-cert-manager:beta   "/usr/bin/tini /bin/…"   9 minutes ago   Up 9 minutes                         snikket-certs
b2905d1e6a55   snikket/snikket-server:beta         "/bin/entrypoint.sh"     9 minutes ago   Up 9 minutes (unhealthy)             snikket
```
```
2021-09-16 04:01:57,661:DEBUG:acme.client:Storing nonce: 0101FdNvbeEep1pMbl1nSiXUXywljWMA7KPHhwCXsaL6SBQ
2021-09-16 04:01:57,662:WARNING:certbot.auth_handler:Challenge failed for domain share.mtz.pw
2021-09-16 04:01:57,662:DEBUG:certbot.error_handler:Calling registered functions
2021-09-16 04:01:57,662:INFO:certbot.auth_handler:Cleaning up challenges
2021-09-16 04:01:57,663:DEBUG:certbot.plugins.webroot:Removing /var/www/.well-known/acme-challenge/X8tQ2vGsftvEzkfH6o9qQvPjDLvnhCXNKP9Bf2T3MpQ
2021-09-16 04:01:57,663:DEBUG:certbot.plugins.webroot:Removing /var/www/.well-known/acme-challenge/aIurlBERu8iDTvGhnZVWpuj5Yz7gkjieDg7yB9tFMYU
2021-09-16 04:01:57,663:DEBUG:certbot.plugins.webroot:Removing /var/www/.well-known/acme-challenge/c1t36Z-IGWT9n8JSxox8FzgoK78V3MnotQRotcPeeh0
2021-09-16 04:01:57,664:DEBUG:certbot.plugins.webroot:All challenges cleaned up
2021-09-16 04:01:57,664:DEBUG:certbot.log:Exiting abnormally:
Traceback (most recent call last):
  File "/usr/bin/certbot", line 11, in <module>
    load_entry_point('certbot==0.31.0', 'console_scripts', 'certbot')()
  File "/usr/lib/python3/dist-packages/certbot/main.py", line 1365, in main
    return config.func(config, plugins)
  File "/usr/lib/python3/dist-packages/certbot/main.py", line 1250, in certonly
    lineage = _get_and_save_cert(le_client, config, domains, certname, lineage)
  File "/usr/lib/python3/dist-packages/certbot/main.py", line 121, in _get_and_save_cert
    lineage = le_client.obtain_and_enroll_certificate(domains, certname)
  File "/usr/lib/python3/dist-packages/certbot/client.py", line 410, in obtain_and_enroll_certificate
    cert, chain, key, _ = self.obtain_certificate(domains)
  File "/usr/lib/python3/dist-packages/certbot/client.py", line 353, in obtain_certificate
    orderr = self._get_order_and_authorizations(csr.data, self.config.allow_subset_of_names)
  File "/usr/lib/python3/dist-packages/certbot/client.py", line 389, in _get_order_and_authorizations
    authzr = self.auth_handler.handle_authorizations(orderr, best_effort)
  File "/usr/lib/python3/dist-packages/certbot/auth_handler.py", line 93, in handle_authorizations
    "Challenges failed for all domains")
certbot.errors.AuthorizationError: Challenges failed for all domains

```

**Comment by vncloudsco** [comment] 2021-09-16 04:30
@mwild1 The cause of the error is image snikket-proxy, we found it didn't work, not accessible via server port 80
 
```
root@xmpp:/var/log# cd nginx/
root@xmpp:/var/log/nginx# ls -la
total 16
drwxr-xr-x 1 root     adm  4096 Feb  2  2021 .
drwxr-xr-x 1 root     root 4096 Feb  2  2021 ..
-rw-r----- 1 www-data adm     0 Feb  2  2021 access.log
-rw-r----- 1 www-data adm     0 Feb  2  2021 error.log
```

**Comment by mwild1** [comment] 2021-09-17 17:43
Hi,

> I tried docker-compose plus up/down/stop/restart but this container doesn't want to retry it's request.

To force a new request you can run the following command:

```
docker-compose exec snikket_certs su letsencrypt -- -c "certbot renew --config-dir /snikket/letsencrypt --cert-path /etc/ssl/certbot --forc
e-renew
```

The certificate authority (Let's Encrypt) have strict [rate limits](https://letsencrypt.org/docs/rate-limits/), so do not run this too many times without fixing the underlying problem. Otherwise it may be impossible for you to get certificates for a period of time.

> If I use other domains on my site and going to use separate directory "/var/www/chat.example.com/" for snikket, then should I change something in configuration?

That's expected. The `root` parameter tells nginx to serve files from a directory. In the case of Snikket, your nginx isn't serving any files but acting as a [reverse proxy](https://en.wikipedia.org/wiki/Reverse_proxy), i.e. it is simply forwarding incoming requests to Snikket. Therefore no root directory is needed or used.

> The certbot got 403 last attempt (the post above) and I'm searching for reason of that.

Confusingly, 403 errors are returned from Let's Encrypt for any failure. Make sure you read the `"detail"` line in the log to find out the actual error that caused the 403 response.

**Comment by xcme** [comment] 2021-09-27 17:35
Thanks. Sorry for the late anwser. I checked the details and see there:
```
{
  "type": "http-01",
  "status": "invalid",
  "error": {
    "type": "urn:ietf:params:acme:error:unauthorized",
    "detail": "Invalid response from http://groups.chat.<mydomainishere>/.well-known/acme-challenge/<somehash> [<myipishere>]: \"\u003c!DOCTYPE html\u003e\\n\u003chtml lang=\\\"en\\\" xmlns:xlink=\\\"http://www.w3.org/1999/xlink\\\"\u003e\\n\\t\u003chead\u003e\\n\\t\\t\u003cmeta charset=\\\"utf-8\\\"\u003e\\n\\t\\t\\n\\t\\t\u003ctitle\u003eSnikket\"",
    "status": 403
}
```

And it repeats for all domains.
Before the first try with Snikket I manually tried to get certs from Let's Encrypt via certbot and it worked. I expect that redirect somewhere works in a wrong way.

**Comment by xcme** [comment] 2021-09-27 17:46
And when I'm trying to open httpS://chat.my.domain then I get 502, which means:
```
The HyperText Transfer Protocol (HTTP) 502 Bad Gateway server error response code indicates that the server, while acting as a gateway or proxy, received an invalid response from the upstream server.
```

And in nginx log I see:
```
connect() failed (111: Connection refused) while connecting to upstream
```

As I mentioned before, I do not see 5443 ports among listening ports, but see 5080 there. Is it a problem or the consequence??

**Comment by Kuuchuu** [comment] 2021-11-20 07:16
I'm having the same issue, status 403 in the letsencrypt log. My proxy stack is SWAG, which uses NGINX. I have the snikket volume symbolically linked to SWAG's directory so I can use snikket's certs in NGINX. All three domains' DNS records are correct and working.

Here is the tail section of my letsencrypt log:
```
2021-11-20 05:40:49,902:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "POST /acme/authz-v3/50996295100 HTTP/1.1" 200 1289
2021-11-20 05:40:49,903:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Sat, 20 Nov 2021 05:40:49 GMT
Content-Type: application/json
Content-Length: 1289
Connection: keep-alive
Boulder-Requester: 287943250
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Replay-Nonce: 0102lU7KQGdgpeL1iYJ3NDqNuZnoqritwss-CPkQY2Rq2gk
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "identifier": {
    "type": "dns",
    "value": "REDACTED.DOMAIN"
  },
  "status": "invalid",
  "expires": "2021-11-27T05:40:45Z",
  "challenges": [
    {
      "type": "http-01",
      "status": "invalid",
      "error": {
        "type": "urn:ietf:params:acme:error:unauthorized",
        "detail": "Invalid response from http://REDACTED.DOMAIN/.well-known/acme-challenge/J3HfbeLmGCIf4C4cvir9ndaCY2qt0Hrc3zqDZhudHeM [XX.XXX.XXX.XXX]: \"\u003chtml\u003e\\r\\n\u003chead\u003e\u003ctitle\u003e502 Bad Gateway\u003c/title\u003e\u003c/head\u003e\\r\\n\u003cbody\u003e\\r\\n\u003ccenter\u003e\u003ch1\u003e502 Bad Gateway\u003c/h1\u003e\u003c/center\u003e\\r\\n\u003chr\u003e\u003ccenter\u003enginx\u003c/cente\"",
        "status": 403
      },
      "url": "https://acme-v02.api.letsencrypt.org/acme/chall-v3/50996295100/sODY7A",
      "token": "J3HfbeLmGCIf4C4cvir9ndaCY2qt0Hrc3zqDZhudHeM",
      "validationRecord": [
        {
          "url": "http://REDACTED.DOMAIN/.well-known/acme-challenge/J3HfbeLmGCIf4C4cvir9ndaCY2qt0Hrc3zqDZhudHeM",
          "hostname": "REDACTED.DOMAIN",
          "port": "80",
          "addressesResolved": [
            "XX.XXX.XXX.XXX"
          ],
          "addressUsed": "XX.XXX.XXX.XXX"
        }
      ],
      "validated": "2021-11-20T05:40:46Z"
    }
  ]
}
2021-11-20 05:40:49,904:DEBUG:acme.client:Storing nonce: 0102lU7KQGdgpeL1iYJ3NDqNuZnoqritwss-CPkQY2Rq2gk
2021-11-20 05:40:49,905:WARNING:certbot.auth_handler:Challenge failed for domain REDACTED.DOMAIN
2021-11-20 05:40:49,905:DEBUG:certbot.error_handler:Calling registered functions
2021-11-20 05:40:49,905:INFO:certbot.auth_handler:Cleaning up challenges
2021-11-20 05:40:49,906:DEBUG:certbot.plugins.webroot:Removing /var/www/.well-known/acme-challenge/T2p4OjqIbFcd4Bp5MnRpjuYNfYyN_UI6N75L0354uHU
2021-11-20 05:40:49,906:DEBUG:certbot.plugins.webroot:Removing /var/www/.well-known/acme-challenge/09zVIX_EfxiGsDUP4Ji9bX2wRXiRqG4pXoqCqC-toOg
2021-11-20 05:40:49,907:DEBUG:certbot.plugins.webroot:Removing /var/www/.well-known/acme-challenge/J3HfbeLmGCIf4C4cvir9ndaCY2qt0Hrc3zqDZhudHeM
2021-11-20 05:40:49,907:DEBUG:certbot.plugins.webroot:All challenges cleaned up
2021-11-20 05:40:49,908:DEBUG:certbot.log:Exiting abnormally:
Traceback (most recent call last):
  File "/usr/bin/certbot", line 11, in <module>
    load_entry_point('certbot==0.31.0', 'console_scripts', 'certbot')()
  File "/usr/lib/python3/dist-packages/certbot/main.py", line 1365, in main
    return config.func(config, plugins)
  File "/usr/lib/python3/dist-packages/certbot/main.py", line 1250, in certonly
    lineage = _get_and_save_cert(le_client, config, domains, certname, lineage)
  File "/usr/lib/python3/dist-packages/certbot/main.py", line 121, in _get_and_save_cert
    lineage = le_client.obtain_and_enroll_certificate(domains, certname)
  File "/usr/lib/python3/dist-packages/certbot/client.py", line 410, in obtain_and_enroll_certificate
    cert, chain, key, _ = self.obtain_certificate(domains)
  File "/usr/lib/python3/dist-packages/certbot/client.py", line 353, in obtain_certificate
    orderr = self._get_order_and_authorizations(csr.data, self.config.allow_subset_of_names)
  File "/usr/lib/python3/dist-packages/certbot/client.py", line 389, in _get_order_and_authorizations
    authzr = self.auth_handler.handle_authorizations(orderr, best_effort)
  File "/usr/lib/python3/dist-packages/certbot/auth_handler.py", line 93, in handle_authorizations
    "Challenges failed for all domains")
certbot.errors.AuthorizationError: Challenges failed for all domains
```
Here is my NGINX conf:
```
server {
    # Accept HTTP connections
    listen 80;
    listen [::]:80;

    server_name REDACTED.DOMAIN;
    server_name groups.REDACTED.DOMAIN;
    server_name share.REDACTED.DOMAIN;

    location / {
        include /config/nginx/proxy.conf;
        include /config/nginx/resolver.conf;
        set $upstream_app localhost;
        set $upstream_port 5080;
        set $upstream_proto http;
        proxy_pass $upstream_proto://$upstream_app:$upstream_port;
        proxy_set_header      Host              $host;
        proxy_set_header      X-Forwarded-For   $proxy_add_x_forwarded_for;

        # A bit of headroom over the 16MB accepted by Prosody.
        client_max_body_size 20M;
    }
}

server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;

    server_name REDACTED.DOMAIN;
    server_name groups.REDACTED.DOMAIN;
    server_name share.REDACTED.DOMAIN;

    #Below line is for SWAG's certbot.
    #include /config/nginx/ssl.conf;
    
    #Commented out until the cert is retrieved so that NGINX doesn't throw errors.
    #ssl_certificate /snikket/letsencrypt/live/REDACTED.DOMAIN/cert.pem;
    #ssl_certificate_key /snikket/letsencrypt/live/REDACTED.DOMAIN/privkey.pem;

    # enable for ldap auth, fill in ldap details in ldap.conf
    #include /config/nginx/ldap.conf;

    # enable for Authelia
    #include /config/nginx/authelia-server.conf;

    location / {
        # enable the next two lines for http auth
        #auth_basic "Restricted";
        #auth_basic_user_file /config/nginx/.htpasswd;

        # enable the next two lines for ldap auth
        #auth_request /auth;
        #error_page 401 =200 /ldaplogin;

        # enable for Authelia
        #include /config/nginx/authelia-location.conf;

        include /config/nginx/proxy.conf;
        include /config/nginx/resolver.conf;
        set $upstream_app localhost;
        set $upstream_port 5443;
        set $upstream_proto http;
        proxy_pass $upstream_proto://$upstream_app:$upstream_port;
        proxy_set_header      Host              $host;
        proxy_set_header      X-Forwarded-For   $proxy_add_x_forwarded_for;
        # REMOVE THIS IF YOU CHANGE `localhost` TO ANYTHING ELSE ABOVE
        proxy_ssl_verify      off;
        proxy_set_header      X-Forwarded-Proto https;
        proxy_ssl_server_name on;

        # A bit of headroom over the 16MB accepted by Prosody.
        client_max_body_size 20M;
    }
}
```
My snikket.conf:
```
# The primary domain of your Snikket instance
SNIKKET_DOMAIN=REDACTED.DOMAIN
# An email address where the admin can be contacted (also used to register your Let's Encrypt account to obtain certificates)
SNIKKET_ADMIN_EMAIL=REDACTED@EMAIL.io

SNIKKET_TWEAK_HTTP_PORT=5080
SNIKKET_TWEAK_HTTPS_PORT=5443
```
Docker-compose.yml remains unchanged.

Any help towards getting Snikket up and running would be greatly appreciated! I'd love to give it a shot. Thanks @mwild1 for your work on the project!

**Comment by mwild1** [comment] 2021-11-25 11:24
Hi folks, sorry for the delay responding here. We recommend the chat for real-time community support: https://snikket.org/contact/

Snikket is working fine for 99% of people, but reverse proxies can introduce a layer of problems and complexity that isn't always easy to debug (everyone's reverse proxy setup is always slightly different).

@xcme If you haven't solved your problem by now (or moved on), port 5443 should certainly be open when everything is working, but it requires certificates first. All you need is to ensure that http:// access on port 80 is working and forwarded to Snikket. You do not need to obtain certificates manually yourself.

@Kuuchuu I've never used it, but doesn't SWAG try to obtain its own certificates from Let's Encrypt? Ideally there should be no need for symlinking in that case.

**Comment by xcme** [comment] 2021-12-17 12:03
Hi @mwild1,

Thanks for answer. I decided to return to this my issue and now trying to investigate it. I just rebuild all my containers from scratch and returned back old _docker-compose.xml_ and now all containers are healthy. I didn't touch nginx config or something else. You may have changed something there since the September, I don't know :)

The question now is about nginx and HTTPS section. It use this file - [reverse_proxy.md](https://github.com/snikket-im/snikket-server/blob/master/docs/advanced/reverse_proxy.md). It has these lines:

```
ssl_certificate /path/to/certificate.pem;
ssl_certificate_key /path/to/key.pem;
```

What should I put there? Should I manually copy certificates from snikket_certs or some magic should happen and solve it automatically?

**Comment by mwild1** [comment] 2021-12-17 13:10
If you use a reverse proxy, it will generally need its own certificates. You can do this with e.g. certbot - there is a [guide here](https://www.nginx.com/blog/using-free-ssltls-certificates-from-lets-encrypt-with-nginx/), and many more online.

Alternatively it's *technically* possible for a reverse proxy to "pass through" HTTPS connections to Snikket without decrypting them - then it doesn't need certificates. But this kind of setup tends to be more complicated and not supported by all proxies.

Thanks for reporting that the original issue is solved. I'll close it now, but feel free to continue commenting if you have any further information or questions, or follow up in our [community chat](https://snikket.org/contact/). Good luck!

**Closed by mwild1** 2021-12-17 13:10 UTC
Labels: question

**Comment by xcme** [comment] 2021-12-17 13:39
I agree, it could be closed. I just copied these certs from snikket_certs and it works :)
Thanks for the help.

**Comment by mwild1** [comment] 2021-12-17 14:28
Excellent!

Note that these will expire after a few months, so copying them one time will not suffice. You could automate it using cron though, for example.
