### ISSUE TITLE
Deleting doesn't change circle user count

### ISSUE THREAD

**Issue by nebunez** [snikket-im/snikket-server#48] opened 2021-07-24 04:19 UTC
I just experienced this today with a test user on my server.

### Steps to reproduce:
1. Create new individual invitation link via Admin > Manage Invitations
2. Use the link to manually create new user
3. Sign into a "legacy" XMPP client (Dino in this case)
4. Send a test message to the circle
5. Delete user via manage users

### Expected:
User is removed from users and circle, and circle count decreases by one

### Actual:
User is removed from users and circle, but the user count of the circle remains the same

**Comment by horazont** [comment] 2021-07-26 16:57
The issue is that user deletion is not caught by `mod_groups_internal`, so the user is never removed from the circle (group).

**Comment by horazont** [comment] 2021-07-26 16:58
As a workaround, you can (at your own risk, best do this supervised by talking to folks in general@channels.snikket.org) use the user purge snippet from here: https://gist.github.com/horazont/1e80c64315dc67dc091ad037914cafd1

**Comment by mwild1** [comment] 2021-11-08 11:56
Fixed in the upcoming release by https://hg.prosody.im/prosody-modules/rev/27f7ed9f50cd

**Closed by mwild1** 2021-11-08 11:56 UTC
