### ISSUE TITLE
Running Snikket behind nginx-proxy-letsencrypt

### ISSUE THREAD

**Issue by mat-l** [snikket-im/snikket-server#8] opened 2020-06-05 08:59 UTC
Dear all,
first of all thank you for your work and this new project :)

I am having some trouble with the set up in my docker environment. I guess it could be a combination with the "nginx-proxy-letsencrypt" container for providing SSL certificates.

For the basic set up I followed the quick-start instructions over here https://snikket.org/service/quickstart/. I extended it environmental variable with the parameters VIRTUAL_HOST=tld, LETSENCRYPT_HOST=tld and the VIRUTAL_PORT=8083. In the set up I cannot just use the ports 80 and 443 case they are used by the nginx-proxy-letsencrypt container for providing SSL certificates to other containers as well.

After deploying the container and generating a invite links with "sudo docker exec snikket create-invite --admin" I am able to ob the link in a browser with a valid SSL certificate. Opening the invitation with the snikket Android App I cannot create the account and/or login. The message is "TLS-handling error".

The logs from the container are not helping me that much:
2020-06-05T08:33:05.938526444Z c2s563a12a8a4b0                     info	Client connected
2020-06-05T08:33:05.960633897Z c2s563a12a8a4b0                     info	Client disconnected: no shared cipher,

In my firewall I have opened the ports as mentioned here: https://github.com/snikket-im/snikket-server/blob/master/docs/advanced/firewall.md

docker-compose:
```
version: "3.3"

services:
  snikket:
    container_name: snikket
    image: snikket/snikket:alpha
    ports:
      - 5222:5222
      - 5269:5269
      - 5000:5000
      - 3478:3478
      - 3479:3479
      - 5349:5349
      - 5350:5350
      - 49152:49152
      - 8083:80
      - 5080:80
      - 5443:443
    env_file: snikket.conf
    restart: unless-stopped
    network_mode: host
    volumes:
      - snikket_data:/snikket
    network_mode: hostingnetwork
    hostname: snikketcontainer

volumes:
  snikket_data:
```

snikket.conf
```
# The primary domain of your Snikket instance
SNIKKET_DOMAIN=tld

# An email address where the admin can be contacted
# (also used to register your Let's Encrypt account to obtain certificates)
SNIKKET_ADMIN_EMAIL=user@tld

VIRTUAL_HOST=tld
LETSENCRYPT_HOST=tld
VIRUTAL_PORT=8083

SNIKKET_TWEAK_HTTP_PORT=5080
SNIKKET_TWEAK_HTTPS_PORT=5443
```

Could you please help me with my setup?
Best regards

**Comment by mwild1** [comment] 2020-06-05 11:25
Hi!

Unfortunately this kind of setup is not supported. Snikket needs certificates for various things. As well as HTTPS, which you observe works through letsencrypt-proxy, Snikket also uses XMPP connections, STUN, TURN (for audio and video calls). Unfortunately none of the magic Let's Encrypt proxies support these protocols.

The good news is that Snikket will obtain and renew its own certificates, so you don't *need* these proxies. However in order to do this, Snikket does need access to port 80 - as this is the only port that the Let's Encrypt folk will connect to for domain verification. If you have something else listening on port 80, it won't work.

The error you see is because Snikket was unable to obtain certificates.

It's not all doom and gloom though! It's a bit more tricky than just following the quickstart guide, but many reverse proxies will be able to listen for traffic on port 80 and route it to the appropriate container. Some initial docs on this kind of setup are at: https://github.com/snikket-im/snikket-server/blob/master/docs/advanced/reverse_proxy.md

These docs are a first draft, so consider that as go through them. If you have suggestions to make, or you try to follow them and something doesn't work, let me know and we can try to figure it out!

P.S. there is one other option, that is so far undocumented. If there is a way that the Snikket container can gain access to the certificates in the letsencrypt container (Docker supports sharing data volumes between multiple containers) then that would be enough to allow Snikket to use the certificates for non-HTTP services. I've not tried this approach yet, and it's likely not officially supported by the proxy container folk, but it may be an easy option.

**Comment by jgerstbe** [comment] 2020-11-17 16:17
Is there an update for using snikket behind a proxy? I set it up using [nginx proxy manager (npm)](https://nginxproxymanager.com/advanced-config/#custom-nginx-configurations) and adding your provided [example conf](https://github.com/snikket-im/snikket-server/blob/master/docs/advanced/reverse_proxy.md) manually. I can not manage the config through npm, but it seems to work fine so far. I mounted the snikket volume into the npm container to access the ssl certificate for the domain. my snikket volume does only include a certificate for the main domian and no certificates for _chat.example.com,  groups.example.com, share.example.com_. Is this the expected behavior? File Upload via the android app works fine, but using gajim there is an certificate error, though I am not sure if upload via gajim worked before.

**Comment by mwild1** [comment] 2020-11-17 16:35
Hi! It sounds like you have everything (mostly) working? Check that https://upload.example.com/ can be accessed ok in your browser. If so, it's probably Gajim or its environment/configuration at fault (they have a support chat: https://gajim.org/development/ ). If your browser can't reach it, then it's a server-side issue.

It's expected that there is only a single certificate (a single certificate can cover multiple domains).

As for updates... I've been making some changes the past week or two to how Snikket obtains certificates. It should be much easier to integrate with other setups once this is rolled out. After documenting that I'll likely close this issue.

**Comment by jgerstbe** [comment] 2020-11-17 17:08
Wow, quick response 😀👍

I checked in the wrong spot before, my bad. The cert is valid for: `example.com, share.example.com, groups.example.com`

The upload subdomain was not mentioned in the quickstart guide or reverse proxy config, it's also missing for the certificate. Should I set it and provide a valid certificate? Gajim indicates `example.com/uploads/` for fileuploads (for messages originating from the app). The Gajim config is not mission critical, I was just curious.

**Comment by mwild1** [comment] 2020-11-17 17:22
Sorry, my mistake! I meant to check share.example.com, not upload!

The Gajim issue is strange... I checked the config but can't see any reason it would pick up a different URL.

**Comment by jgerstbe** [comment] 2020-11-17 17:40
I found the culprit...it was an outdated gajim version. It's working fine now 👍 thanks for your help.

**Comment by sonicnkt** [comment] 2020-12-28 14:09
I want to try snicket but i also have a nginx proxy running which uses port 80/443. 
Since i created a new dyn domain just for snikket im fine with snikket handling the certificates. 

Last thing i was wondering is what would be the best way to let my ngninx container access the snicket certificates and where is the privkey and fullchain stored?

**Comment by jgerstbe** [comment] 2020-12-28 15:45
I mounted the snikket volume into my npm container at `/snikket` as read only. The cert can then be accessed like this in the nginx config file.

```
  ssl_certificate /snikket/letsencrypt/live/<your-ulr>/cert.pem;
  ssl_certificate_key /snikket/letsencrypt/live/<your-ulr>/privkey.pem;
```

**Comment by mwild1** [comment] 2021-02-04 15:31
Closing this, as multiple people are running Snikket behind reverse proxies just fine now. We need to get the documentation polished and added properly to the website, but that's a different task.

**Closed by mwild1** 2021-02-04 15:31 UTC
