### ISSUE TITLE
run server on subdomain, jabber-id on domain

### ISSUE THREAD

**Issue by xundeenergie** [snikket-im/snikket-server#23] opened 2021-02-06 23:59 UTC
How can i configure, that my id is user@domain.tld, but the server runs on chat.domain.at?

**Comment by mwild1** [comment] 2021-02-08 09:22
Hi, this is not currently supported. Maybe one day :)

The problem is that in such a setup the XMPP server needs certificates for `domain.tld`. We currently use Let's Encrypt, and that requires access to port 80 for the domain we need (e.g. `http://domain.tld/`).

There are some workarounds, but they are not very easy and we are trying to keep Snikket as simple as possible.

In the future we may figure out a way to make this easy. For now it is easier to just have JIDs on a subdomain.

Possible workarounds right now are:

- ACME DNS challenges (instead of HTTP challenges)
- A reverse proxy on your site (`domain.tld`) that forwards the necessary requests from Let's Encrypt to Snikket
- Integrate and deploy POSH ([RFC 7711](https://tools.ietf.org/html/rfc7711))

Probably all of these would require changes to Snikket to be usable.

I'm going to close this issue because this isn't something we can take action on right now. The feature is on our wishlist and when we have a plan and resources to implement it, we will definitely do so :)

**Closed by mwild1** 2021-02-08 09:22 UTC
